### ISSUE TITLE
Export strict `Parser`

### ISSUE THREAD

**Issue by fregante** [g-plane/typed-query-selector#25]
It seems that the `Parse` interface isn't exported from ./strict:

https://github.com/g-plane/typed-query-selector/blob/559be6c0eeb2a1629c488958091a83198eacec09/strict.d.ts#L62

so I can't replace `import type {ParseSelector} from 'typed-query-selector/parser'` with a stricter version in:

https://github.com/refined-github/refined-github/blob/65c58aed2ceb98e50c9112e7ef0428821033742e/source/helpers/types.d.ts#L2

**Comment by g-plane** [comment]
Do you need the strict parser?

**Comment by fregante** [comment]
Yes, I'd like to try it in Refined GitHub; I have several APIs that make use of typed-query-selector so it would be good to also use it to validate the selectors (if it works as expected. I never used it)

**Comment by stof** [comment]
Actually, instead of exporting it from the same file than the one patching `Element.querySelector()`, it should probably be split into a separate `strict-parser` file, that could allow importing the strict parser type without patching the DOM APIs. Otherwise, it is unsafe for libraries to depend on the strict parser for their own API (as they would have the side-effect of patching globals).

**Comment by fregante** [comment]
Could you release this change?

**Comment by g-plane** [comment]
Released [v2.8.0](https://www.npmjs.com/package/typed-query-selector/v/2.8.0).
